name: vibe_verse
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_animate: ^4.5.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  geolocator: ^12.0.0
  permission_handler: ^11.3.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  path_provider: ^2.1.4
  intl: ^0.19.0
  google_fonts: ^6.2.1
  firebase_core: ^3.3.0
  firebase_analytics: ^11.2.1
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  cloud_firestore: ^5.2.1
  persistent_bottom_nav_bar: ^6.2.1
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0
  pull_to_refresh: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/social_media.png"

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#FFFFFF"
  image: "assets/images/social_media.png"



flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf

    - family: Gang
      fonts:
        - asset: assets/fonts/Gang_Three.ttf

    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Medium.otf
        - asset: assets/fonts/Satoshi-Black.otf

