// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXmy9JeYElOPuykytVRHwPHwu7AmSQ4jA',
    appId: '1:682732307316:web:bbfa0e62d1362473c72221',
    messagingSenderId: '682732307316',
    projectId: 'vibe-verse-631fc',
    authDomain: 'vibe-verse-631fc.firebaseapp.com',
    storageBucket: 'vibe-verse-631fc.appspot.com',
    measurementId: 'G-4RS61XVJ9E',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJzFxB7uLrNaDZKS5levF-ECOYVrWu18s',
    appId: '1:682732307316:ios:f9a2c6512fe04974c72221',
    messagingSenderId: '682732307316',
    projectId: 'vibe-verse-631fc',
    storageBucket: 'vibe-verse-631fc.appspot.com',
    iosBundleId: 'com.example.vibeVerse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXmy9JeYElOPuykytVRHwPHwu7AmSQ4jA',
    appId: '1:682732307316:web:564d76d554125dabc72221',
    messagingSenderId: '682732307316',
    projectId: 'vibe-verse-631fc',
    authDomain: 'vibe-verse-631fc.firebaseapp.com',
    storageBucket: 'vibe-verse-631fc.appspot.com',
    measurementId: 'G-K1K355WMXZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJzFxB7uLrNaDZKS5levF-ECOYVrWu18s',
    appId: '1:682732307316:ios:f9a2c6512fe04974c72221',
    messagingSenderId: '682732307316',
    projectId: 'vibe-verse-631fc',
    storageBucket: 'vibe-verse-631fc.appspot.com',
    iosBundleId: 'com.example.vibeVerse',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNfP_oGKv452C7Kf6lCHdX-QGUCpLcjm0',
    appId: '1:682732307316:android:af801de9b047ac29c72221',
    messagingSenderId: '682732307316',
    projectId: 'vibe-verse-631fc',
    storageBucket: 'vibe-verse-631fc.appspot.com',
  );

}